spring:
  profiles:
    active: local
    group:
      local:
      dev:
      deploy:
    include:
      - secret
      - common
      - redis
  mail:
    host: smtp.gmail.com
    port: 587
    username: pjm9673@gmail.com
    password: ukvrktucwoesehon
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000