### 1. 보드 등록 API
POST http://localhost:8080/boards
Content-Type: application/json

{
  "name": "Spring 업무공유",
  "bgColor": "white",
  "description": "hanghaero 업무공유"
}

### 2. 보드 수정 API
PUT http://localhost:8080/boards/1
Content-Type: application/json

{
  "name": "Spring project",
  "bgColor": "black",
  "description": "hanghaero 업무공유 update"
}