### 1.로그인후 토큰 받기
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "email":"pjm9673@gmail.com",
  "password":"@Qkrwjdals96"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}

### 1. 보드 등록 API
POST http://localhost:8080/boards
Content-Type: application/json

{
  "name": "Spring 업무공유",
  "bgColor": "white",
  "description": "hanghaero 업무공유"
}

### 2. 보드 수정 API
PUT http://localhost:8080/boards/1
Content-Type: application/json

{
  "name": "Spring project",
  "bgColor": "black",
  "description": "hanghaero 업무공유 update"
}

### 3. 보드 삭제 API
DELETE http://localhost:8080/boards/1
Content-Type: application/json
