### 1.로그인후 토큰 받기
POST http://localhost:8080/api/user/signin
Content-Type: application/json

{
  "email":"admin@test.com",
  "password":"@Qkrwjdals96"
}

> {%
    client.global.set("access_token", response.headers.valueOf("Authorization"));
    client.log(client.global.get("access_token"));
%}

### 2. 보드에 칼럼 등록
POST http://localhost:8080/columns
Content-Type: application/json
Authorization: {{access_token}}

{
  "boardId": 2,
  "title" : "화요일 TO DO"
}

### 2. 보드에 있는 칼럼 수정
PUT http://localhost:8080/columns/7
Content-Type: application/json
Authorization: {{access_token}}

{
  "boardId" : 2,
  "title" : "수요일 TO DO"
}

### 3. 보드에 있는 칼럼 삭제
DELETE http://localhost:8080/columns/7?boardId=2
Content-Type: application/json
Authorization: {{access_token}}

### 4. 칼럼 이동
PUT http://localhost:8080/columns/8/to/5?boardId=2
Content-Type: application/json
Authorization: {{access_token}}